.TH "src/strcspn.c" 3 "Sun Apr 11 2021" "strcspn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/strcspn.c
.SH SYNOPSIS
.br
.PP
\fC#include 'header\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBStrCSpn\fP (const char *str, const char *reject)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int StrCSpn (const char * str, const char * reject)"

.SH "Author"
.PP 
Generated automatically by Doxygen for strcspn from the source code\&.
