.TH "hdr/header.h" 3 "Sun Apr 11 2021" "strchr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hdr/header.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX\fP   100"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBStrChr\fP (const char *s, int c)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX   100"

.SH "Function Documentation"
.PP 
.SS "char* StrChr (const char * s, int c)"

.SH "Author"
.PP 
Generated automatically by Doxygen for strchr from the source code\&.
