.TH "src/main.c" 3 "Sun Apr 11 2021" "strchr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c \- strchr  

.SH SYNOPSIS
.br
.PP
\fC#include 'header\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
strchr 


.PP
\fBAuthor\fP
.RS 4
lakshmi 
.RE
.PP
\fBDate\fP
.RS 4
11/04/2021 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for strchr from the source code\&.
