.TH "src/strchr.c" 3 "Sun Apr 11 2021" "strchr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/strchr.c
.SH SYNOPSIS
.br
.PP
\fC#include 'header\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBStrChr\fP (const char *string, int c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* StrChr (const char * string, int c)"

.SH "Author"
.PP 
Generated automatically by Doxygen for strchr from the source code\&.
